"""initial schema

Revision ID: 3bd70519ad3c
Revises: 
Create Date: 2026-05-03 12:34:28.642086
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bd70519ad3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_logs_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_logs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('keyword_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_groups_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_groups_user_id'), ['user_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('login_method', sa.String(length=32), nullable=False),
    sa.Column('phone_mask', sa.String(length=32), nullable=True),
    sa.Column('qr_id', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('qr_url', sa.Text(), nullable=True),
    sa.Column('encrypted_temp_cookies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_configs_model_type'), ['model_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_configs_user_id'), ['user_id'], unique=False)

    op.create_table('monitoring_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_targets_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_targets_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_targets_user_id'), ['user_id'], unique=False)

    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=32), nullable=True),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_accounts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('account_cookie_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_cookies', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_cookie_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_cookie_versions_platform_account_id'), ['platform_account_id'], unique=False)

    op.create_table('monitoring_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_snapshots_target_id'), ['target_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('note_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_platform_account_id'), ['platform_account_id'], unique=False)

    op.create_table('ai_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_drafts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_drafts_user_id'), ['user_id'], unique=False)

    op.create_table('note_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_assets_note_id'), ['note_id'], unique=False)

    op.create_table('note_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=128), nullable=True),
    sa.Column('created_at_remote', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_comments_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_comments_note_id'), ['note_id'], unique=False)

    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_table('ai_generated_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['ai_drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generated_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generated_assets_user_id'), ['user_id'], unique=False)

    op.create_table('publish_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('source_draft_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('publish_mode', sa.String(length=32), nullable=False),
    sa.Column('publish_options', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('external_note_id', sa.String(length=128), nullable=False),
    sa.Column('publish_error', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_draft_id'], ['ai_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_jobs_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_jobs_platform_account_id'), ['platform_account_id'], unique=False)

    op.create_table('publish_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_job_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('upload_status', sa.String(length=32), nullable=False),
    sa.Column('creator_media_id', sa.String(length=128), nullable=False),
    sa.Column('upload_error', sa.Text(), nullable=False),
    sa.Column('creator_upload_info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['publish_job_id'], ['publish_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_assets_publish_job_id'), ['publish_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_assets_publish_job_id'))

    op.drop_table('publish_assets')
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_jobs_platform_account_id'))
        batch_op.drop_index(batch_op.f('ix_publish_jobs_platform'))

    op.drop_table('publish_jobs')
    with op.batch_alter_table('ai_generated_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generated_assets_user_id'))

    op.drop_table('ai_generated_assets')
    op.drop_table('note_tags')
    with op.batch_alter_table('note_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_comments_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_comments_comment_id'))

    op.drop_table('note_comments')
    with op.batch_alter_table('note_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_assets_note_id'))

    op.drop_table('note_assets')
    with op.batch_alter_table('ai_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_drafts_platform'))

    op.drop_table('ai_drafts')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_platform_account_id'))
        batch_op.drop_index(batch_op.f('ix_notes_platform'))
        batch_op.drop_index(batch_op.f('ix_notes_note_id'))

    op.drop_table('notes')
    with op.batch_alter_table('monitoring_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_snapshots_target_id'))

    op.drop_table('monitoring_snapshots')
    with op.batch_alter_table('account_cookie_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_cookie_versions_platform_account_id'))

    op.drop_table('account_cookie_versions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_platform'))

    op.drop_table('tasks')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))

    op.drop_table('tags')
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_platform_accounts_id'))

    op.drop_table('platform_accounts')
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_target_type'))
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_platform'))

    op.drop_table('monitoring_targets')
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_configs_model_type'))

    op.drop_table('model_configs')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_platform'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('keyword_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_groups_user_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_groups_platform'))

    op.drop_table('keyword_groups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_logs_platform'))

    op.drop_table('api_logs')
    # ### end Alembic commands ###
