"""add auto_tasks table

Revision ID: df3b1005390e
Revises: fc35ffa0c18b
Create Date: 2026-05-03 20:45:39.030063
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df3b1005390e'
down_revision: Union[str, None] = 'fc35ffa0c18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('pc_account_id', sa.Integer(), nullable=False),
    sa.Column('creator_account_id', sa.Integer(), nullable=False),
    sa.Column('crawl_count', sa.Integer(), nullable=False),
    sa.Column('daily_publish_count', sa.Integer(), nullable=False),
    sa.Column('ai_instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('total_published', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['pc_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_tasks_user_id'))

    op.drop_table('auto_tasks')
    # ### end Alembic commands ###
