"""add monitoring crawl fields

Revision ID: fc35ffa0c18b
Revises: b7626fb8d48a
Create Date: 2026-05-03 13:03:44.796583
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc35ffa0c18b'
down_revision: Union[str, None] = 'b7626fb8d48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crawl_interval_minutes', sa.Integer(), nullable=False, server_default='60'))
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_crawl_error', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_monitoring_targets_platform_account_id', 'platform_accounts', ['platform_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_monitoring_targets_platform_account_id', type_='foreignkey')
        batch_op.drop_column('last_crawl_error')
        batch_op.drop_column('consecutive_failures')
        batch_op.drop_column('crawl_interval_minutes')
        batch_op.drop_column('platform_account_id')

    # ### end Alembic commands ###
